service: aws-lambda-image-resizer
frameworkVersion: "2"
provider:
  name: aws
  runtime: nodejs12.x
  profile: yeeeeees
  region: us-east-1
plugins:
  - serverless-s3-local
  - serverless-offline
custom:
  s3:
    host: localhost
    directory: ./tmp
resources:
  Resources:
    NewResource:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: resize-images
functions:
  resize:
    handler: handler.resize
    events:
      - s3:
          bucket: 2020-1224-aws-lambda-image-resizer
          event: s3:ObjectCreated:*
          existing: true

