service: image-resizer
frameworkVersion: "2"
provider:
  name: aws
  runtime: nodejs12.x
  profile: yeeeeees
  region: us-east-1
  timeout: 20
  environment:
    ENV: production
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "s3:GetObject"
      Resource: "arn:aws:s3:::image-resizer/*"
    - Effect: "Allow"
      Action:
        - "s3:PutObject"
      Resource: "arn:aws:s3:::image-resizer/*"
resources:
  Resources:
    imageResizerBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: image-resizer
functions:
  resize:
    handler: handler.resize
    events:
      - s3:
          bucket: image-resizer
          event: s3:ObjectCreated:*
          existing: true
          rules:
            - prefix: originals/
