version: "3"
services:
  api:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - ./src:/app/src
  postgres:
    image: postgres:latest
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: "yes"
      POSTGRES_PASSWORD: "yes"
      POSTGRES_DB: "yes"
