apiVersion: v1
kind: ConfigMap
metadata:
  name: testconfig
data:
  PORT: "3001"
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: api-deployment
  labels:
    app: api
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - image: api
          imagePullPolicy: Never
          name: api
          ports:
            - containerPort: 3001
          envFrom:
            - configMapRef:
                name: testconfig
---
apiVersion: v1
kind: Service
metadata:
  name: api-service
  labels:
    app: api
spec:
  type: NodePort
  selector:
    app: api
  ports:
    - protocol: TCP
      port: 3001
      targetPort: 3001
