service: hiiiike-bot
useDotend: true
frameworkVersion: "2"
provider:
  runtime: nodejs12.x
  name: aws
  profile: yeeeeees
  region: ap-northeast-1
  timeout: 20
  logs:
    restApi: true
plugins:
  - serverless-offline
  - serverless-dotenv-plugin
functions:
  weathers:
    handler: handler.weathers
    events:
      - http: GET /weathers
  weatherBot:
    handler: handler.weatherBot
    events:
      - http: POST /weather/bot
