apiVersion: v1
kind: ConfigMap
metadata:
  name: env
data:
  FOO: "bar"
  PORT: "3002"
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: api-deployment
  labels:
    app: api
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - image: api
          imagePullPolicy: Never
          name: api
          ports:
            - containerPort: 3002
          envFrom:
            - configMapRef:
                name: env      
---
apiVersion: v1
kind: Service
metadata:
  name: api-service
  labels:
    app: api
spec:
  type: NodePort
  selector:
    app: api
  ports:
    - protocol: TCP
      port: 3002
      targetPort: 3002
      nodePort: 30003
# ---
# apiVersion: networking.k8s.io/v1beta1
# kind: Ingress
# metadata:
#   name: test-ingress
#   annotations:
#     nginx.ingress.kubernetes.io/rewrite-target: /
# spec:
#   rules:
#     - host: test.haha
#       http:
#         paths:
#           - path: /
#             backend:
#               serviceName: api-service
#               servicePort: 3002
