version: "3"
services:
  api:
    build: .
    ports:
      - "3000:3000"
    links:
      - redis
  redis:
    image: redis
    volumes:
      - .:/code
      - logvolume01:/var/log
volumes:
  logvolume01: {}
