version: "3"
services:
  api:
    build: ./api
    image: api
    volumes:
      - ./api:/app
    # image: hiiamyes/packaging-backend:1.0.0
    ports:
      - "4000:3000"
  postgres:
    image: postgres:9.6.11-alpine
    environment:
      POSTGRES_PASSWORD: postgres
