version: "3"
services:
  api:
    build: .
    # ports:
    #   - "3000:3000"
    networks:
      - netcore-dev
    depends_on:
      - postgres

  postgres:
    image: postgres:latest
    volumes:
      - ~/postgresql/data:/var/lib/postgresql/data
    expose:
      - 5432
    environment:
      - POSTGRES_DB=${PGDATABASE}
      - POSTGRES_USER=${PGUSER}
      - POSTGRES_PASSWORD=${PGPASSWORD}
    networks:
      - netcore-dev
    ports:
      - ${PGPORT}:5432
    
networks:
  netcore-dev:
